name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8080
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache-dependency-path: ./go.sum

      - name: Build
        run: go build -v ./...

      - name: Run App & Tests
        run: |
          go run cmd/url-shortener/main.go &
          sleep 5

          go test -v ./...

          pkill -f "url-shortener"
