name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8080
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache-dependency-path: ./go.sum

      - name: Setup
        run: cp .env.example .env

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: |
          go test -v ./...
